### ISSUE TITLE
invalid byte sequence in US-ASCII when fingerprinting url

### ISSUE THREAD

**Issue by pyc0de** [erwanlr/Fingerprinter#19]
root@kali:~/tools/Fingerprinter# ./fingerprinter.rb -a drupal -f https://drupal.org
invalid byte sequence in US-ASCII
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:89:in `strip!'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:89:in `block (2 levels) in parse'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:88:in `each_line'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:88:in `block in parse'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:128:in `initialize'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:87:in `new'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:87:in `parse'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:52:in `default'
/var/lib/gems/2.3.0/gems/public_suffix-2.0.5/lib/public_suffix.rb:118:in `valid?'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.37.9/lib/cms_scanner/target/scope.rb:52:in `<<'
/var/lib/gems/2

**Comment by erwanlr** [comment]
If upgrading ruby is an option, please try it. I have no issues with ruby 2.3.3

**Comment by pyc0de** [comment]
apparently I have 2.3.3:

root@kali:~# ruby --version
ruby 2.3.3p222 (2016-11-21) [arm-linux-gnueabihf]

**Comment by pyc0de** [comment]
Resolved. 
export LANG=en_US.UTF-8
