### ISSUE TITLE
[Feature Request] Struts

### ISSUE THREAD

**Issue by riramar** [erwanlr/Fingerprinter#35]
I was trying to find a way to identify Struts servers. Have you already tried that?

**Comment by erwanlr** [comment]
Targets using framework are usually hard to fingerprint, as the framework doesn't really leave much of it.

Do you have an example of a website using Struts ?

**Comment by riramar** [comment]
Sorry for the delay... just found this interesting list https://wiki.apache.org/struts/PoweredBy on the web.

Examples of websites built using Struts

http://www.virtual.unal.edu.co - UNVirtual, Colombian e-learning Website of National University of Colombia. build on STRUTS, Tiles, Velocity and Lucene cooming soon, all on SUN AppServer9.

http://www.boston.com - Boston MA, USA Newspaper (The Boston Globe) portal (owned by the NY Times Co.) Their login pages are an obvious Struts application on a Sun Application server v8.1 at their http://members.boston.com/reg/login.do url.

Bazaaria is an online trading platform which focuses on online-bargaining. Bazaaria uses the Struts library for all its pages.

http://bof-web.com - Best of five. Managing your Squash/Badminton/Tennis Championships. Using STRUTS on Tomcat.

http://www.oneentry.com - Compare International Moving Quotes & Overseas Shipping. Using STRUTS on Tomcat 5.0

http://www.elasticpath.com Elastic Path - eCommerce software utilizing Struts, Velocity, Hibernate

http://www.unclassified.com.au - Unclassified is Australia's 100% FREE online classifieds service (struts/tiles,hibernate,lucene)

http://www.iphonecard.com.au - Prepaid phone cards & international calling cards calling from Australia (struts,tiles,hibernate,spring2,freemarker)

http://www.rosa.com - Swiss Technology Integrator (Struts, Tiles, Hibernate, Spring)

Blogverzeichnis - A blog directory for German-language Blogs)

Blog-Feed - A RSS directory for German-language blog feeds)

http://www.showtimetickets.com (after market ticket broker)

http://www.juliannegiffin.com (uses Struts for logins, editing users, forums, tracking downloads etc.)

http://www.mixermixer.com

http://sourceforge.net/projects/personalblog (weblog done with struts/tiles/hibernate)

http://echofloripa.sytes.net/personalblog (an instance of the last version of Personalblog - see above))

http://www.nieleyde.com/ (another instance of the last version of the blog)

http://www.e-boss.gr (the e-Business One Stop Shop for Greek SMEs)

http://www.auto-domain.com (the online automotive super maill)

http://www.corsair.fr (the air booking site, uses lucene and struts including validator and tiles)

http://www.678voli.it (air booking site in Italy)

http://gislab.cifor.cgiar.org/fsic (a forestry related metadata information catalog)

http://www.sarunas.lv (forum build on Struts)

http://www.myuhc.com (UnitedHealthcare's personalized health and benefits website)

http://www.sussexenterprise.co.uk (Chamber of Commerce for Sussex, UK)

http://www.telecomfinance.com (Financial journal and newsletter)

http://www.ideasfactory.com (Career portal for the creative industries - Channel 4 UK)

http://www.asw2.net (Online school)

http://dublin.citycollective.com (Online community for Dubliners, featuring small ads, personals and forums)

http://www.raumverwaltung.de (Online room management - equipment and catering service)

http://www.telewest.co.uk/ (large UK Telco)

http://www.blueyonder.co.uk (Leading UK ISP)

http://www.aerlingus.com (Irish Airline)

http://www.cidental.com (Dental Discount Plans)

http://www.dentalinsurancess.com/ (Dental Discount Plans)

http://www.nurse-anesthetist-schools.com/ (CRNA program directory using Struts on Tomcat 5.0)

http://www.makeastorybook.com (uses Struts for logins, flow of user interface etc.)

https://www.foodcourtlive.com (an online foodcourt specifically designed for people working in Raritan center NJ)

http://demo.raibledesigns.com/struts-resume (an online resume building/viewing system)

http://www.esagegroup.com - eSage Group A consulting company, most of our projects are built on Tomcat.

http://www.ebia.com - Employee Benefits Institute of America provided COBRA and 401K Law Reviews

http://www.agileedge.com - Agility Bug Tracker

http://telemetry.logica.co.uk - Master Control - telemetry on the web, produced by LogicaCMG built on Tomcat.

http://www.theuniquepear.com - ECommerce Site - Stylish Home Decor and Accessories

http://www.hotelsandaccommodation.com.au/ - Several parts of hotelsandaccommodation.com.au use Struts

http://bugs.sun.com/bugdatabase - Sun's bug tracker for Java

http://www.vodafone.co.uk/livestudio - Vodafone's multimedia site for MMS devices

http://www.wissen.de - A German knowledge portal

http://www.shopbloomfield.com - eCommerce nutrition site. Built on Resin.

http://www.virgin-atlantic.com - Airline site.

http://www.citimortgage.com/ - CitiGroup's mortgage division

http://www.lockheedmartin.com - Defense company

http://www.yell.com - (Yellow Pages UK)

http://www.manhattanministorage.com/ - A New York City based mini-storage rental house.

http://www.21st.com - 21st Century Insurance, California-based insurance company (active as of Oct 2005)

http://www.nationalcar.com - National Car Rental (active as of Oct 2005)

http://www.alamo.com - Alamo Car Rental, active as of Oct 2005.

http://www.babacar.org - Baba Car Rental, active as of Oct 2005.

Reengineered by Perot Systems in 2004 using Linux/OAS/J2EE/Struts stack for Vanguard Car Rental, owner of the National and Alamo car rental brands.

http://www.3java.net - A comprehensive directory of Java(tm) open source software, as well as an evaluation system that aids in the selection of open source software. Developed with Struts & Velocity.

http://www.discounttire.com - Discout Tire Company (as of Jan 2006)

http://1up.com - The family of gaming sites, part of Ziff Davis network. As of March 2006 uses Struts/Tiles/iBATIS 2.x running on cluster out of 6 Resin servers. Previous version used Microsoft ASP technology.

http://www.orangepics.com - Simple, Safe Photo Sharing (as of June 2006)

http://www.edmunds.com - Auto prices and reviews. Uses Struts/Tiles along with Spring/Hibernate/EJB stack running on WebLogic server (as of June 2006)

http://www.realoem.com - BMW auto & moto online parts catalog (as of June 2006)

http://www.upickhome.com - Home ownership via rent-to-own (as of July 2006)

http://www.rd.com - Reader's Digest Website(as of July 2006) Previous version had been built with MS ASP (according to Netcraft.com).

http://www.bridgerfunding.com - commercial funding company (as of July 2006)

http://www.tirekingdom.com - Tire Kingdom, tire and automotive services retailer in the United States (as of July 2006)

http://www.irs.gov - Internal Revenue Service, portions of website (as of 2004-2006)

http://www.cj.com - Commission Junction, online advertising and affiliate marketing (as of July 2006)

http://www.amnestyusa.org - Amnesty International USA (as of August 2006)

http://www.contratacionesparaguay.gov.py/denuncia - Sistema de denuncias de casos de corrupción

http://www.officedepot.com - Office Depot, Inc., a seller of office products (as of August 2006)

http://www.circuitcity.com - a seller of TVs and consumer electronics products (as of August 2006)

http://www.marvell.com - a provider or storage, communications and consumer silicon solutions (as of August 2006)

http://www.dmv.ca.gov - California Department of Motor Vehicles (August 2006: portions of the site, like vehicle registration renewal form, registration fee calculator, appointment manager, occupational license information system)

http://www.sho.com - Showtime Networks Inc., premium television network (as of August 2006)

http://www.shoesathome.com - Shoesathome.com, online shoe shop for Netherlands and Belgium.

http://www.sears.com - Sears, Roebuck and Co. offers a wide range of home merchandise, apparel and automotive products and services through more than 2,400 Sears-branded and affiliated stores in the United States and Canada.

http://www.jobbank.com - Employment site for job searches, posting jobs, posting resumes, and career tools. This MVC site uses Struts for its controller along with Tiles, Velocity, and other Apache projects.

http://www.fueleconomy.gov/mpg - This section of www.fueleconomy.gov website allows visitors to track and share fuel consumption of their vehicles (as of February 2007)

http://www.zap2it.com - Online TV guide and program listings (as of February 2007)

http://www.thisislondon.co.uk - Online news from the Evening Standard (as of March 2007)

http://trkcnfrm.smi.usps.com - Track & Confirm module of United States Postal Service (as of April 2007)

http://www.johndeeregifts.com - Official merchandise (hats, clothing, toys) of John Deere company (as of April 2007)

http://www.theshoppingchannel.com - Online portal of a Canadian broadcast retailer (as of April 2007)

See also:

StrutsWebLinks page for the list of third party software built on Struts.

Simon Chappel website for a list of sites using struts.

**Comment by erwanlr** [comment]
Thank you :)

Unfortunately, this list is outdated and the websites I checked from it are not running Struts anymore.

I found one misconfigured using Shodan (http://123.57.44.182:8181), but couldn't identify any fingerprints on it.

So far it's not worth to add Struts

**Comment by riramar** [comment]
That's ok. Thanks for trying anyway. :)
