### ISSUE TITLE
Ruby 2.5.3 / 2.6.0 - Bundler error

### ISSUE THREAD

**Issue by Hax0rG1rl** [erwanlr/Fingerprinter#36]
Hi, 

I'm using a rbenv and I'm trying to deploy/use the last version of Fingerprinter. 

I encounter the following error message trying to initiate bundle install:

```
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.6)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.6)' in any of the relevant sources:
  the local ruby installation
```

Got it tested under Kali Linux latest / Ubuntu 16.04, Ruby 2.5.3 /  2.6.0.

Do you have any ideas on how I would be able to overcome this situation? 

Also, would be too much to ask for a docker version of this. I'd say this way would be much easier for you to manage version control of the core and avoid too many issues to be open :) 

Thanks!

**Comment by erwanlr** [comment]
pull the latest changes and ```bundle install``` again.

Regarding a docker image, I am not using docker at all but will have a look in the next few days. However, if you are familiar with docker, any PR for the Dockerfile would be appreciated :)

**Comment by Hax0rG1rl** [comment]
Hi,

Thanks. Tested the fix and it works like a charm.

In regards docker not quite but would be an interesting learning curve. I
will try to invest some time into this.

Thank you!
