### ISSUE TITLE
Log timeout, don't quit

### ISSUE THREAD

**Issue by exploresecurity** [erwanlr/Fingerprinter#41]
A timeout exits the script, which I found to be too harsh. I've edited /lib/fingerprint.rb to comment the exception raised in line 16 and added:
```
if res.timed_out?
  puts "[WARNING] Timeout for #{res.effective_url}"
end
```
Perhaps something to consider.
Thanks for the tool.

**Comment by erwanlr** [comment]
Implemented for the fingerprinting and unique fingerprinting.
