### ISSUE TITLE
Add web2py

### ISSUE THREAD

**Issue by martinbydefault** [erwanlr/Fingerprinter#43]
www.web2py.com
https://github.com/web2py/web2py

**Comment by erwanlr** [comment]
Added, a few notes:

- Latest version is 2.18.5 according to their website, but is not in the GitHub releases 
- Success may vary depending on how the target application is configured. I've had success with some, while no results with others. When you try to fingerprint an application, it might be necessary to target the parent folder (ie https://target.com/somefolder/ -> https://target.com/)
